export const DATA = [
	// МЫШИ (10 товаров)
	{
		id: 1,
		name: 'Razer Viper Ultimate',
		category: 'Мыши',
		price: 9990,
		brand: 'Razer',
		rating: 4.8,
		features: {
			type: 'Беспроводная',
			sensor: 'Оптический',
			dpi: 20000,
			buttons: 8,
			weight: 74,
			connection: 'USB Dongle',
			rgb: true,
		},
		image: '/images/razer-viper-ultimate.jpg',
		inStock: true,
		discount: 10,
		isNew: false,
	},
	{
		id: 2,
		name: 'Logitech G502 HERO',
		category: 'Мыши',
		price: 5990,
		brand: 'Logitech',
		rating: 4.7,
		features: {
			type: 'Проводная',
			sensor: 'Оптический HERO',
			dpi: 25600,
			buttons: 11,
			weight: 121,
			connection: 'USB',
			rgb: true,
		},
		image: '/images/logitech-g502.jpg',
		inStock: true,
		discount: 5,
		isNew: false,
	},
	{
		id: 3,
		name: 'SteelSeries Rival 3',
		category: 'Мыши',
		price: 3990,
		brand: 'SteelSeries',
		rating: 4.5,
		features: {
			type: 'Проводная',
			sensor: 'Оптический',
			dpi: 8500,
			buttons: 6,
			weight: 77,
			connection: 'USB',
			rgb: true,
		},
		image: '/images/steelseries-rival3.jpg',
		inStock: true,
		discount: 0,
		isNew: true,
	},
	{
		id: 4,
		name: 'HyperX Pulsefire Haste',
		category: 'Мыши',
		price: 4590,
		brand: 'HyperX',
		rating: 4.6,
		features: {
			type: 'Проводная',
			sensor: 'Оптический',
			dpi: 16000,
			buttons: 6,
			weight: 59,
			connection: 'USB',
			rgb: true,
		},
		image: '/images/hyperx-pulsefire-haste.jpg',
		inStock: true,
		discount: 15,
		isNew: false,
	},
	{
		id: 5,
		name: 'Razer DeathAdder V2',
		category: 'Мыши',
		price: 6990,
		brand: 'Razer',
		rating: 4.7,
		features: {
			type: 'Проводная',
			sensor: 'Оптический',
			dpi: 20000,
			buttons: 8,
			weight: 82,
			connection: 'USB',
			rgb: true,
		},
		image: '/images/razer-deathadder.jpg',
		inStock: true,
		discount: 0,
		isNew: false,
	},
	{
		id: 6,
		name: 'Logitech G Pro Wireless',
		category: 'Мыши',
		price: 11990,
		brand: 'Logitech',
		rating: 4.9,
		features: {
			type: 'Беспроводная',
			sensor: 'HERO',
			dpi: 25600,
			buttons: 8,
			weight: 80,
			connection: 'Lightspeed',
			rgb: true,
		},
		image: '/images/logitech-g-pro-wireless.jpg',
		inStock: true,
		discount: 8,
		isNew: false,
	},
	{
		id: 7,
		name: 'Corsair Dark Core RGB Pro',
		category: 'Мыши',
		price: 8490,
		brand: 'Corsair',
		rating: 4.4,
		features: {
			type: 'Беспроводная',
			sensor: 'Оптический',
			dpi: 18000,
			buttons: 8,
			weight: 133,
			connection: 'USB/Bluetooth',
			rgb: true,
		},
		image: '/images/corsair-dark-core.jpg',
		inStock: false,
		discount: 12,
		isNew: false,
	},
	{
		id: 8,
		name: 'ASUS ROG Gladius II',
		category: 'Мыши',
		price: 5490,
		brand: 'ASUS',
		rating: 4.3,
		features: {
			type: 'Проводная',
			sensor: 'Оптический',
			dpi: 12000,
			buttons: 7,
			weight: 110,
			connection: 'USB',
			rgb: true,
		},
		image: '/images/asus-rog-gladius.jpg',
		inStock: true,
		discount: 20,
		isNew: false,
	},
	{
		id: 9,
		name: 'Razer Basilisk X Hyperspeed',
		category: 'Мыши',
		price: 4990,
		brand: 'Razer',
		rating: 4.5,
		features: {
			type: 'Беспроводная',
			sensor: 'Оптический',
			dpi: 16000,
			buttons: 6,
			weight: 83,
			connection: 'Bluetooth',
			rgb: false,
		},
		image: '/images/razer-basilisk.jpg',
		inStock: true,
		discount: 0,
		isNew: true,
	},
	{
		id: 10,
		name: 'SteelSeries Aerox 3',
		category: 'Мыши',
		price: 7990,
		brand: 'SteelSeries',
		rating: 4.6,
		features: {
			type: 'Беспроводная',
			sensor: 'TrueMove Air',
			dpi: 18000,
			buttons: 6,
			weight: 66,
			connection: 'USB/Bluetooth',
			rgb: true,
		},
		image: '/images/steelseries-aerox3.jpg',
		inStock: true,
		discount: 5,
		isNew: true,
	},

	// КЛАВИАТУРЫ (8 товаров)
	{
		id: 11,
		name: 'Logitech G Pro X Mechanical',
		category: 'Клавиатуры',
		price: 12990,
		brand: 'Logitech',
		rating: 4.7,
		features: {
			type: 'Механическая',
			switch: 'GX Blue Clicky',
			backlight: 'RGB',
			connection: 'USB',
			size: 'TKL',
			material: 'Пластик',
			hotSwap: true,
		},
		image: '/images/logitech-g-pro-kb.jpg',
		inStock: true,
		discount: 0,
		isNew: true,
	},
	{
		id: 12,
		name: 'Razer BlackWidow V3',
		category: 'Клавиатуры',
		price: 8990,
		brand: 'Razer',
		rating: 4.6,
		features: {
			type: 'Механическая',
			switch: 'Razer Green',
			backlight: 'RGB',
			connection: 'USB',
			size: 'Full-size',
			material: 'Алюминий',
			hotSwap: false,
		},
		image: '/images/razer-blackwidow.jpg',
		inStock: false,
		discount: 20,
		isNew: false,
	},
	{
		id: 13,
		name: 'SteelSeries Apex Pro',
		category: 'Клавиатуры',
		price: 15990,
		brand: 'SteelSeries',
		rating: 4.8,
		features: {
			type: 'Механическая',
			switch: 'OmniPoint',
			backlight: 'RGB',
			connection: 'USB',
			size: 'Full-size',
			material: 'Алюминий',
			hotSwap: false,
		},
		image: '/images/steelseries-apex-pro.jpg',
		inStock: true,
		discount: 10,
		isNew: false,
	},
	{
		id: 14,
		name: 'HyperX Alloy Origins Core',
		category: 'Клавиатуры',
		price: 7990,
		brand: 'HyperX',
		rating: 4.7,
		features: {
			type: 'Механическая',
			switch: 'HyperX Red',
			backlight: 'RGB',
			connection: 'USB',
			size: 'TKL',
			material: 'Алюминий',
			hotSwap: false,
		},
		image: '/images/hyperx-alloy-origins.jpg',
		inStock: true,
		discount: 15,
		isNew: false,
	},
	{
		id: 15,
		name: 'Corsair K70 RGB TKL',
		category: 'Клавиатуры',
		price: 10990,
		brand: 'Corsair',
		rating: 4.5,
		features: {
			type: 'Механическая',
			switch: 'Cherry MX Red',
			backlight: 'RGB',
			connection: 'USB',
			size: 'TKL',
			material: 'Алюминий',
			hotSwap: false,
		},
		image: '/images/corsair-k70.jpg',
		inStock: true,
		discount: 0,
		isNew: true,
	},
	{
		id: 16,
		name: 'Razer Huntsman Mini',
		category: 'Клавиатуры',
		price: 7990,
		brand: 'Razer',
		rating: 4.4,
		features: {
			type: 'Механическая',
			switch: 'Razer Optical',
			backlight: 'RGB',
			connection: 'USB',
			size: '60%',
			material: 'Пластик',
			hotSwap: false,
		},
		image: '/images/razer-huntsman-mini.jpg',
		inStock: true,
		discount: 8,
		isNew: false,
	},
	{
		id: 17,
		name: 'Logitech G813 LIGHTSYNC',
		category: 'Клавиатуры',
		price: 11990,
		brand: 'Logitech',
		rating: 4.6,
		features: {
			type: 'Механическая',
			switch: 'GL Clicky',
			backlight: 'RGB',
			connection: 'USB',
			size: 'Full-size',
			material: 'Алюминий',
			hotSwap: false,
		},
		image: '/images/logitech-g813.jpg',
		inStock: true,
		discount: 12,
		isNew: false,
	},
	{
		id: 18,
		name: 'ASUS ROG Strix Scope',
		category: 'Клавиатуры',
		price: 8990,
		brand: 'ASUS',
		rating: 4.3,
		features: {
			type: 'Механическая',
			switch: 'Cherry MX Brown',
			backlight: 'RGB',
			connection: 'USB',
			size: 'Full-size',
			material: 'Алюминий',
			hotSwap: false,
		},
		image: '/images/asus-rog-strix.jpg',
		inStock: true,
		discount: 25,
		isNew: false,
	},

	// НАУШНИКИ (7 товаров)
	{
		id: 19,
		name: 'SteelSeries Arctis Pro',
		category: 'Наушники',
		price: 15990,
		brand: 'SteelSeries',
		rating: 4.9,
		features: {
			type: 'Полноразмерные',
			connection: 'Проводные',
			microphone: true,
			frequency: '10-40000 Hz',
			impedance: '32 Ohm',
			wireless: false,
		},
		image: '/images/steelseries-arctis-pro.jpg',
		inStock: true,
		discount: 15,
		isNew: false,
	},
	{
		id: 20,
		name: 'HyperX Cloud II',
		category: 'Наушники',
		price: 7990,
		brand: 'HyperX',
		rating: 4.8,
		features: {
			type: 'Полноразмерные',
			connection: 'USB/3.5mm',
			microphone: true,
			frequency: '15-25000 Hz',
			impedance: '60 Ohm',
			wireless: false,
		},
		image: '/images/hyperx-cloud-ii.jpg',
		inStock: true,
		discount: 10,
		isNew: false,
	},
	{
		id: 21,
		name: 'Razer BlackShark V2 Pro',
		category: 'Наушники',
		price: 12990,
		brand: 'Razer',
		rating: 4.7,
		features: {
			type: 'Полноразмерные',
			connection: 'Беспроводные',
			microphone: true,
			frequency: '12-28000 Hz',
			impedance: '32 Ohm',
			wireless: true,
		},
		image: '/images/razer-blackshark.jpg',
		inStock: true,
		discount: 0,
		isNew: true,
	},
	{
		id: 22,
		name: 'Logitech G733 LIGHTSYNC',
		category: 'Наушники',
		price: 10990,
		brand: 'Logitech',
		rating: 4.5,
		features: {
			type: 'Полноразмерные',
			connection: 'Беспроводные',
			microphone: true,
			frequency: '20-20000 Hz',
			impedance: '35 Ohm',
			wireless: true,
		},
		image: '/images/logitech-g733.jpg',
		inStock: true,
		discount: 18,
		isNew: false,
	},
	{
		id: 23,
		name: 'Corsair Virtuoso RGB Wireless',
		category: 'Наушники',
		price: 13990,
		brand: 'Corsair',
		rating: 4.6,
		features: {
			type: 'Полноразмерные',
			connection: 'Беспроводные',
			microphone: true,
			frequency: '20-40000 Hz',
			impedance: '32 Ohm',
			wireless: true,
		},
		image: '/images/corsair-virtuoso.jpg',
		inStock: false,
		discount: 22,
		isNew: false,
	},
	{
		id: 24,
		name: 'ASUS ROG Delta Core',
		category: 'Наушники',
		price: 6990,
		brand: 'ASUS',
		rating: 4.4,
		features: {
			type: 'Полноразмерные',
			connection: 'USB/3.5mm',
			microphone: true,
			frequency: '20-20000 Hz',
			impedance: '32 Ohm',
			wireless: false,
		},
		image: '/images/asus-rog-delta.jpg',
		inStock: true,
		discount: 30,
		isNew: false,
	},
	{
		id: 25,
		name: 'SteelSeries Arctis 7',
		category: 'Наушники',
		price: 11990,
		brand: 'SteelSeries',
		rating: 4.7,
		features: {
			type: 'Полноразмерные',
			connection: 'Беспроводные',
			microphone: true,
			frequency: '20-20000 Hz',
			impedance: '32 Ohm',
			wireless: true,
		},
		image: '/images/steelseries-arctis7.jpg',
		inStock: true,
		discount: 14,
		isNew: true,
	},
]
