export const DATA = [
	// МЫШИ (10 товаров)
	{
		id: 0,
		name: 'Razer Viper Ultimate',
		category: 'Мыши',
		price: 9990,
		brand: 'Razer',
		rating: 4.8,
		description:
			'Беспроводная игровая мышь премиум-класса с ультра-быстрыми оптическими переключателями и зарядной док-станцией. Идеальный баланс веса и производительности для соревновательных игр.',
		features: {
			type: 'Беспроводная',
			sensor: 'Оптический',
			dpi: 20000,
			buttons: 8,
			weight: 74,
			connection: 'USB Dongle',
			rgb: true,
		},
		image: '/images/razer-viper-ultimate.jpg',
		inStock: true,
		discount: 10,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: true,
	},
	{
		id: 1,
		name: 'Razer DeathAdder V2',
		category: 'Мыши',
		price: 5990,
		brand: 'Razer',
		rating: 4.7,
		description:
			'Обновленная версия культовой эргономичной мыши. Идеальна для хвата ладонью, оснащена оптическими переключателями для мгновенного отклика и улучшенными тефлоновыми ножками.',
		features: {
			type: 'Проводная',
			sensor: 'Оптический Focus+',
			dpi: 20000,
			buttons: 8,
			weight: 82,
			connection: 'USB',
			rgb: true,
		},
		image: '/images/razer-deathadder-v2.jpg',
		inStock: true,
		discount: 0,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 2,
		name: 'Logitech G502 HERO',
		category: 'Мыши',
		price: 5990,
		brand: 'Logitech',
		rating: 4.7,
		description:
			'Легендарная проводная мышь с гиперскоростной прокруткой и регулируемым весом. Имеет 11 программируемых кнопок и улучшенный сенсор HERO 25K для максимальной точности.',
		features: {
			type: 'Проводная',
			sensor: 'Оптический HERO 25K',
			dpi: 25600,
			buttons: 11,
			weight: 121,
			connection: 'USB',
			rgb: true,
		},
		image: '/images/logitech-g502-hero.jpg',
		inStock: true,
		discount: 5,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 3,
		name: 'SteelSeries Rival 3',
		category: 'Мыши',
		price: 3990,
		brand: 'SteelSeries',
		rating: 4.5,
		description: 'Доступная проводная мышь с потрясающей RGB-подсветкой Prism и надежным сенсором TrueMove Core. Отличный стартовый выбор для начинающих геймеров.',
		features: {
			type: 'Проводная',
			sensor: 'Оптический TrueMove Core',
			dpi: 8500,
			buttons: 6,
			weight: 77,
			connection: 'USB',
			rgb: true,
		},
		image: '/images/steelseries-rival3.jpg',
		inStock: true,
		discount: 0,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: true,
	},
	{
		id: 4,
		name: 'HyperX Pulsefire Haste',
		category: 'Мыши',
		price: 4590,
		brand: 'HyperX',
		rating: 4.6,
		description: 'Невероятно легкая (59г) проводная мышь с перфорированным корпусом для лучшей вентиляции. Имеет съемный кабель и PTFE ножки для плавного скольжения.',
		features: {
			type: 'Проводная',
			sensor: 'Оптический Pixart 3335',
			dpi: 16000,
			buttons: 6,
			weight: 59,
			connection: 'USB',
			rgb: true,
		},
		image: '/images/hyperx-pulsefire-haste.jpg',
		inStock: true,
		discount: 15,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 5,
		name: 'Razer Basilisk X Hyperspeed',
		category: 'Мыши',
		price: 6990,
		brand: 'Razer',
		rating: 4.7,
		description: 'Беспроводная игровая мышь с поддержкой Bluetooth и технологии Hyperspeed для игр. Работает до 450 часов от одной батарейки AA и имеет 6 программируемых кнопок.',
		features: {
			type: 'Беспроводная',
			sensor: 'Оптический 5G',
			dpi: 16000,
			buttons: 6,
			weight: 83,
			connection: 'Bluetooth / 2.4GHz',
			rgb: false,
		},
		image: '/images/razer-basilisk-x.jpg',
		inStock: true,
		discount: 0,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 6,
		name: 'Logitech G Pro Wireless',
		category: 'Мыши',
		price: 11990,
		brand: 'Logitech',
		rating: 4.9,
		description: 'Беспроводная мышь, созданная в сотрудничестве с киберспортсменами. Имеет симметричную форму, технологию LIGHTSPEED с задержкой 1 мс и сенсор HERO 25K.',
		features: {
			type: 'Беспроводная',
			sensor: 'HERO 25K',
			dpi: 25600,
			buttons: 8,
			weight: 80,
			connection: 'Lightspeed',
			rgb: true,
		},
		image: '/images/logitech-g-pro-wireless.jpg',
		inStock: true,
		discount: 8,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 7,
		name: 'Corsair Dark Core RGB Pro',
		category: 'Мыши',
		price: 8490,
		brand: 'Corsair',
		rating: 4.4,
		description:
			'Беспроводная мышь с регулируемой боковой панелью для индивидуальной настройки. Поддерживает быструю зарядку Qi, имеет 8 программируемых кнопок и сенсор 18000 DPI.',
		features: {
			type: 'Беспроводная',
			sensor: 'Оптический PixArt PAW3392',
			dpi: 18000,
			buttons: 8,
			weight: 133,
			connection: 'USB/Bluetooth',
			rgb: true,
		},
		image: '/images/corsair-dark-core.jpg',
		inStock: false,
		discount: 12,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 8,
		name: 'ASUS ROG Gladius II',
		category: 'Мыши',
		price: 5490,
		brand: 'ASUS',
		rating: 4.3,
		description: 'Игровая мышь с уникальной функцией горячей замены переключателей (без пайки). Имеет эргономичную форму для правшей и настраиваемую RGB-подсветку Aura Sync.',
		features: {
			type: 'Проводная',
			sensor: 'Оптический PMW3360',
			dpi: 12000,
			buttons: 7,
			weight: 110,
			connection: 'USB',
			rgb: true,
		},
		image: '/images/asus-rog-gladius.jpg',
		inStock: true,
		discount: 20,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 9,
		name: 'SteelSeries Aerox 3 Wireless',
		category: 'Мыши',
		price: 7990,
		brand: 'SteelSeries',
		rating: 4.6,
		description: 'Сверхлегкая беспроводная мышь весом 66г с перфорированным корпусом и защитой от воды IP54. Оснащена сенсором TrueMove Air и поддерживает быструю зарядку USB-C.',
		features: {
			type: 'Беспроводная',
			sensor: 'TrueMove Air',
			dpi: 18000,
			buttons: 6,
			weight: 66,
			connection: 'USB/Bluetooth',
			rgb: true,
		},
		image: '/images/steelseries-aerox3-wireless.jpg',
		inStock: true,
		discount: 5,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: true,
	},

	// КЛАВИАТУРЫ (8 товаров)
	{
		id: 10,
		name: 'Logitech G Pro X Mechanical',
		category: 'Клавиатуры',
		price: 12990,
		brand: 'Logitech',
		rating: 4.7,
		description:
			'Профессиональная механическая клавиатура TKL формата с возможностью горячей замены переключателей. Имеет минималистичный дизайн и настраиваемую RGB-подсветку LIGHTSYNC.',
		features: {
			type: 'Механическая',
			switch: 'GX Blue Clicky (Hot-swap)',
			backlight: 'RGB',
			connection: 'USB',
			size: 'TKL',
			material: 'Пластик',
			hotSwap: true,
		},
		image: '/images/logitech-g-pro-x-kb.jpg',
		inStock: true,
		discount: 0,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: true,
	},
	{
		id: 11,
		name: 'Razer BlackWidow V3',
		category: 'Клавиатуры',
		price: 8990,
		brand: 'Razer',
		rating: 4.6,
		description:
			'Полноразмерная механическая клавиатура с переключателями Razer Green для тактильного и кликающего отклика. Имеет программируемые макроклавиши и мягкий упор для запястий.',
		features: {
			type: 'Механическая',
			switch: 'Razer Green',
			backlight: 'RGB Chroma',
			connection: 'USB',
			size: 'Full-size',
			material: 'Алюминиевая верхняя панель',
			hotSwap: false,
		},
		image: '/images/razer-blackwidow-v3.jpg',
		inStock: false,
		discount: 20,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 12,
		name: 'SteelSeries Apex Pro',
		category: 'Клавиатуры',
		price: 15990,
		brand: 'SteelSeries',
		rating: 4.8,
		description:
			'Инновационная механическая клавиатура с регулируемым ходом клавиш OmniPoint. Позволяет настраивать точку срабатывания от 0.4 до 3.6 мм. Имеет OLED-дисплей и алюминиевую раму.',
		features: {
			type: 'Механическая (регулируемая)',
			switch: 'OmniPoint',
			backlight: 'RGB',
			connection: 'USB',
			size: 'Full-size',
			material: 'Алюминий',
			hotSwap: false,
		},
		image: '/images/steelseries-apex-pro.jpg',
		inStock: true,
		discount: 10,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 13,
		name: 'HyperX Alloy Origins Core',
		category: 'Клавиатуры',
		price: 7990,
		brand: 'HyperX',
		rating: 4.7,
		description: 'Компактная механическая клавиатура TKL формата с авиационным алюминиевым корпусом и переключателями HyperX Red. Имеет яркую RGB-подсветку с эффектами.',
		features: {
			type: 'Механическая',
			switch: 'HyperX Red Linear',
			backlight: 'RGB',
			connection: 'USB',
			size: 'TKL',
			material: 'Алюминий',
			hotSwap: false,
		},
		image: '/images/hyperx-alloy-origins-core.jpg',
		inStock: true,
		discount: 15,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 14,
		name: 'Corsair K70 RGB TKL',
		category: 'Клавиатуры',
		price: 10990,
		brand: 'Corsair',
		rating: 4.5,
		description: 'Беспроводная механическая клавиатура TKL формата с переключателями Cherry MX. Поддерживает технологии SLIPSTREAM WIRELESS и BLUETOOTH с временем отклика 1 мс.',
		features: {
			type: 'Механическая',
			switch: 'Cherry MX Red',
			backlight: 'RGB per-key',
			connection: 'USB / Bluetooth / 2.4GHz',
			size: 'TKL',
			material: 'Алюминий',
			hotSwap: false,
		},
		image: '/images/corsair-k70-tkl.jpg',
		inStock: true,
		discount: 0,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: true,
	},
	{
		id: 15,
		name: 'Razer Huntsman Mini',
		category: 'Клавиатуры',
		price: 7990,
		brand: 'Razer',
		rating: 4.4,
		description: 'Ультракомпактная 60% клавиатура с оптическими переключателями для мгновенного отклика. Идеальна для экономии места на столе и портативного использования.',
		features: {
			type: 'Механическая (оптическая)',
			switch: 'Razer Optical Linear',
			backlight: 'RGB Chroma',
			connection: 'USB-C',
			size: '60%',
			material: 'Пластик',
			hotSwap: false,
		},
		image: '/images/razer-huntsman-mini.jpg',
		inStock: true,
		discount: 8,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 16,
		name: 'Logitech G813 LIGHTSYNC',
		category: 'Клавиатуры',
		price: 11990,
		brand: 'Logitech',
		rating: 4.6,
		description:
			'Низкопрофильная механическая клавиатура с переключателями GL и алюминиевой рамкой толщиной всего 22 мм. Имеет мультимедийные клавиши и тонкий профиль для комфорта.',
		features: {
			type: 'Механическая (низкопрофильная)',
			switch: 'GL Clicky',
			backlight: 'RGB LIGHTSYNC',
			connection: 'USB',
			size: 'Full-size',
			material: 'Алюминий',
			hotSwap: false,
		},
		image: '/images/logitech-g813.jpg',
		inStock: true,
		discount: 12,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 17,
		name: 'ASUS ROG Strix Scope',
		category: 'Клавиатуры',
		price: 8990,
		brand: 'ASUS',
		rating: 4.3,
		description: 'Игровая механическая клавиатура с уникальной широкой клавишей Ctrl для удобства в шутерах. Имеет алюминиевую верхнюю панель и переключатели Cherry MX.',
		features: {
			type: 'Механическая',
			switch: 'Cherry MX Brown',
			backlight: 'RGB Aura Sync',
			connection: 'USB',
			size: 'Full-size',
			material: 'Алюминий',
			hotSwap: false,
		},
		image: '/images/asus-rog-strix-scope.jpg',
		inStock: true,
		discount: 25,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},

	// НАУШНИКИ (7 товаров)
	{
		id: 18,
		name: 'SteelSeries Arctis Pro',
		category: 'Наушники',
		price: 15990,
		brand: 'SteelSeries',
		rating: 4.9,
		description: 'Проводные игровые наушники Hi-Res с двойными аудиодрайверами для разделения высоких и низких частот. Включают внешний ЦАП и систему очистки ClearCast.',
		features: {
			type: 'Полноразмерные',
			connection: 'Проводные (с ЦАП)',
			microphone: true,
			frequency: '10-40000 Hz',
			impedance: '32 Ohm',
			wireless: false,
		},
		image: '/images/steelseries-arctis-pro.jpg',
		inStock: true,
		discount: 15,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 19,
		name: 'HyperX Cloud II',
		category: 'Наушники',
		price: 7990,
		brand: 'HyperX',
		rating: 4.8,
		description: 'Проводные наушники с виртуальным объемным звуком 7.1 и съемным микрофоном. Имеют прочную алюминиевую раму и память формы амбушюр.',
		features: {
			type: 'Полноразмерные',
			connection: 'Проводные (USB/3.5mm)',
			microphone: true,
			frequency: '15-25000 Hz',
			impedance: '60 Ohm',
			wireless: false,
		},
		image: '/images/hyperx-cloud-ii.jpg',
		inStock: true,
		discount: 10,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 20,
		name: 'Razer BlackShark V2 Pro',
		category: 'Наушники',
		price: 12990,
		brand: 'Razer',
		rating: 4.7,
		description: 'Беспроводные игровые наушники с технологией HyperSpeed. Оснащены направленными драйверами TriForce Titanium 50 мм и съемным микрофоном с шумоподавлением.',
		features: {
			type: 'Полноразмерные',
			connection: 'Беспроводные',
			microphone: true,
			frequency: '12-28000 Hz',
			impedance: '32 Ohm',
			wireless: true,
		},
		image: '/images/razer-blackshark-v2-pro.jpg',
		inStock: true,
		discount: 0,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: true,
	},
	{
		id: 21,
		name: 'Logitech G733 LIGHTSYNC',
		category: 'Наушники',
		price: 10990,
		brand: 'Logitech',
		rating: 4.5,
		description: 'Беспроводные наушники с подсветкой LIGHTSYNC и двойными слоями сетки для комфорта. Имеют технологию Blue VO!CE для чистого голоса и время работы до 29 часов.',
		features: {
			type: 'Полноразмерные',
			connection: 'Беспроводные',
			microphone: true,
			frequency: '20-20000 Hz',
			impedance: '35 Ohm',
			wireless: true,
		},
		image: '/images/logitech-g733.jpg',
		inStock: true,
		discount: 18,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 22,
		name: 'Corsair Virtuoso RGB Wireless',
		category: 'Наушники',
		price: 13990,
		brand: 'Corsair',
		rating: 4.6,
		description:
			'Беспроводные наушники премиум-класса с алюминиевыми ушками и вещательным микрофоном с качеством 24бит/96кГц. Поддерживают проводное, беспроводное и Bluetooth подключение.',
		features: {
			type: 'Полноразмерные',
			connection: 'Беспроводные / Bluetooth / USB',
			microphone: true,
			frequency: '20-40000 Hz',
			impedance: '32 Ohm',
			wireless: true,
		},
		image: '/images/corsair-virtuoso.jpg',
		inStock: false,
		discount: 22,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 23,
		name: 'ASUS ROG Delta Core',
		category: 'Наушники',
		price: 6990,
		brand: 'ASUS',
		rating: 4.4,
		description: 'Проводные игровые наушники с драйверами Essence 50 мм и технологией виртуального объемного звука. Имеют гибридную амбушюру и легкую конструкцию.',
		features: {
			type: 'Полноразмерные',
			connection: 'USB/3.5mm',
			microphone: true,
			frequency: '20-20000 Hz',
			impedance: '32 Ohm',
			wireless: false,
		},
		image: '/images/asus-rog-delta-core.jpg',
		inStock: true,
		discount: 30,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 24,
		name: 'SteelSeries Arctis 7',
		category: 'Наушники',
		price: 11990,
		brand: 'SteelSeries',
		rating: 4.7,
		description: 'Беспроводные наушники с технологией Lossless 2.4 ГГц для аудио без задержек. Имеют время работы до 24 часов, систему ClearCast и аудиомикшер ChatMix.',
		features: {
			type: 'Полноразмерные',
			connection: 'Беспроводные',
			microphone: true,
			frequency: '20-20000 Hz',
			impedance: '32 Ohm',
			wireless: true,
		},
		image: '/images/steelseries-arctis7.jpg',
		inStock: true,
		discount: 14,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: true,
	},
	{
		id: 25,
		name: 'Razer Kraken Tournament Edition',
		category: 'Наушники',
		price: 8990,
		brand: 'Razer',
		rating: 4.5,
		description: 'Проводные наушники с контроллером THX Spatial Audio для точного позиционирования звука в играх. Имеют охлаждающие гелевые подушечки и выдвижной микрофон.',
		features: {
			type: 'Полноразмерные',
			connection: 'Проводные (USB)',
			microphone: true,
			frequency: '12-28000 Hz',
			impedance: '32 Ohm',
			wireless: false,
		},
		image: '/images/razer-kraken-te.jpg',
		inStock: true,
		discount: 0,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 26,
		name: 'Glorious Model O Wireless',
		category: 'Мыши',
		price: 7490,
		brand: 'Glorious',
		rating: 4.8,
		description: 'Ультралегкая беспроводная мышь с дырявым дизайном для максимальной воздушности и производительности. Идеальна для FPS игр.',
		features: {
			type: 'Беспроводная',
			sensor: 'BAMF',
			dpi: 19000,
			buttons: 6,
			weight: 69,
			connection: 'USB Dongle',
			rgb: true,
		},
		image: '/images/glorious-model-o-wireless.jpg',
		inStock: true,
		discount: 0,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: true,
	},
	{
		id: 27,
		name: 'Endgame Gear XM1r',
		category: 'Мыши',
		price: 6490,
		brand: 'Endgame Gear',
		rating: 4.6,
		description: 'Проводная мышь с лучшим в своем классе сенсором и формой, созданной для когтевого и пальцевого хвата.',
		features: {
			type: 'Проводная',
			sensor: 'PixArt PAW3370',
			dpi: 19000,
			buttons: 5,
			weight: 70,
			connection: 'USB',
			rgb: false,
		},
		image: '/images/endgame-xm1r.jpg',
		inStock: true,
		discount: 8,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 28,
		name: 'Pulsar X2 Wireless',
		category: 'Мыши',
		price: 8990,
		brand: 'Pulsar',
		rating: 4.9,
		description: 'Беспроводная мышь премиум-класса с невероятно низкой задержкой, идеальной симметричной формой и долгим временем работы от батареи.',
		features: {
			type: 'Беспроводная',
			sensor: 'PAW3395',
			dpi: 26000,
			buttons: 5,
			weight: 52,
			connection: 'USB Dongle/Bluetooth',
			rgb: true,
		},
		image: '/images/pulsar-x2-wireless.jpg',
		inStock: true,
		discount: 0,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: true,
	},
	{
		id: 29,
		name: 'Zowie EC2-C',
		category: 'Мыши',
		price: 6990,
		brand: 'Zowie',
		rating: 4.7,
		description: 'Культовая эргономичная мышь для правшей, созданная для профессиональных киберспортсменов. Без RGB, только чистая производительность.',
		features: {
			type: 'Проводная',
			sensor: 'PixArt 3360',
			dpi: 3200,
			buttons: 5,
			weight: 73,
			connection: 'USB',
			rgb: false,
		},
		image: '/images/zowie-ec2-c.jpg',
		inStock: true,
		discount: 0,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},

	// КЛАВИАТУРЫ (добавляем 4 новых, всего 12)
	{
		id: 30,
		name: 'Keychron Q3',
		category: 'Клавиатуры',
		price: 14990,
		brand: 'Keychron',
		rating: 4.9,
		description: 'Кастомная механическая клавиатура TKL формата в алюминиевом корпусе с поддержкой QMK/VIA, горячей заменой свитчей и потрясающим звуком.',
		features: {
			type: 'Механическая',
			switch: 'Gateron G Pro Red (Hot-swap)',
			backlight: 'RGB',
			connection: 'USB-C',
			size: 'TKL',
			material: 'Алюминий',
			hotSwap: true,
		},
		image: '/images/keychron-q3.jpg',
		inStock: true,
		discount: 5,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: true,
	},
	{
		id: 31,
		name: 'Ducky One 3 SF',
		category: 'Клавиатуры',
		price: 10990,
		brand: 'Ducky',
		rating: 4.8,
		description: 'Компактная 65% клавиатура с двойными PBT кейкапами, горячей заменой свитчей Cherry MX и регулируемыми ножками.',
		features: {
			type: 'Механическая',
			switch: 'Cherry MX Silent Red (Hot-swap)',
			backlight: 'RGB',
			connection: 'USB-C',
			size: '65%',
			material: 'Пластик',
			hotSwap: true,
		},
		image: '/images/ducky-one3-sf.jpg',
		inStock: false,
		discount: 0,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 32,
		name: 'Wooting 60HE',
		category: 'Клавиатуры',
		price: 17990,
		brand: 'Wooting',
		rating: 5.0,
		description:
			'Игровая клавиатура нового поколения с аналоговыми магнитными переключателями Lekker. Позволяет регулижать ход клавиши и обеспечивает максимальную скорость срабатывания.',
		features: {
			type: 'Аналоговая магнитная',
			switch: 'Lekker Linear 60',
			backlight: 'RGB',
			connection: 'USB-C',
			size: '60%',
			material: 'Пластик/Алюминий',
			hotSwap: true,
		},
		image: '/images/wooting-60he.jpg',
		inStock: true,
		discount: 0,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: true,
	},
	{
		id: 33,
		name: 'Royal Kludge RK84',
		category: 'Клавиатуры',
		price: 5990,
		brand: 'Royal Kludge',
		rating: 4.4,
		description: 'Бюджетная беспроводная механическая клавиатура 75% формата с поддержкой Bluetooth, 2.4G и проводного подключения. Отличный выбор для начала.',
		features: {
			type: 'Механическая',
			switch: 'RK Red',
			backlight: 'RGB',
			connection: 'Bluetooth/2.4G/USB-C',
			size: '75%',
			material: 'Пластик',
			hotSwap: false,
		},
		image: '/images/rk84.jpg',
		inStock: true,
		discount: 20,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},

	// НАУШНИКИ (добавляем 3 новых, всего 10)
	{
		id: 34,
		name: 'Beyerdynamic DT 990 Pro',
		category: 'Наушники',
		price: 12990,
		brand: 'Beyerdynamic',
		rating: 4.8,
		description: 'Легендарные студийные открытые наушники для профессионалов. Обладают невероятно детальным и широким звучанием, идеальны для игр и анализа звука.',
		features: {
			type: 'Полноразмерные (открытые)',
			connection: 'Проводные',
			microphone: false,
			frequency: '5-35000 Hz',
			impedance: '250 Ohm',
			wireless: false,
		},
		image: '/images/beyerdynamic-dt990.jpg',
		inStock: true,
		discount: 10,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 35,
		name: 'Audeze Maxwell Wireless',
		category: 'Наушники',
		price: 23990,
		brand: 'Audeze',
		rating: 4.9,
		description: 'Беспроводные игровые наушники премиум-класса с планарными магнитными драйверами. Звук высочайшего качества, долгий срок работы батареи и съемный микрофон.',
		features: {
			type: 'Полноразмерные',
			connection: 'Беспроводные (2.4G/Bluetooth)',
			microphone: true,
			frequency: '10-50000 Hz',
			impedance: 'N/A',
			wireless: true,
		},
		image: '/images/audeze-maxwell.jpg',
		inStock: true,
		discount: 0,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: true,
	},
	{
		id: 36,
		name: 'EPOS H6Pro',
		category: 'Наушники',
		price: 9990,
		brand: 'EPOS',
		rating: 4.6,
		description: 'Комфортные закрытые наушники с двумя типами амбушюр (тканевые и кожзам) и отстегивающимся микрофоном с чистым звучанием.',
		features: {
			type: 'Полноразмерные (закрытые)',
			connection: 'Проводные',
			microphone: true,
			frequency: '10-30000 Hz',
			impedance: '30 Ohm',
			wireless: false,
		},
		image: '/images/epos-h6pro.jpg',
		inStock: true,
		discount: 15,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},

	// НОВЫЕ КАТЕГОРИИ:

	// КОВРИКИ ДЛЯ МЫШИ (6 товаров)
	{
		id: 37,
		name: 'SteelSeries QcK Heavy',
		category: 'Коврики',
		price: 2490,
		brand: 'SteelSeries',
		rating: 4.7,
		description: 'Легендарный толстый тканевый коврик (6 мм). Обеспечивает идеальную поверхность для скольжения и амортизацию для запястья.',
		features: {
			type: 'Тканевый',
			size: 'XL (450x400x6 мм)',
			surface: 'Контролируемое',
			base: 'Резиновая',
			stichedEdges: false,
			design: 'Черный матовый',
		},
		image: '/images/ss-qck-heavy.jpg',
		inStock: true,
		discount: 0,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 38,
		name: 'Logitech G840 XL',
		category: 'Коврики',
		price: 4990,
		brand: 'Logitech',
		rating: 4.5,
		description: 'Огромный коврик, покрывающий стол. Низкофрикционная поверхность оптимизирована для сенсоров Logitech G.',
		features: {
			type: 'Тканевый',
			size: 'XXL (900x400x3 мм)',
			surface: 'Скользящее',
			base: 'Резиновая',
			stichedEdges: true,
			design: 'Черный с логотипом',
		},
		image: '/images/logitech-g840.jpg',
		inStock: true,
		discount: 10,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 39,
		name: 'Razer Strider Chroma',
		category: 'Коврики',
		price: 6990,
		brand: 'Razer',
		rating: 4.4,
		description: 'Гибридный коврик со скоростной поверхностью и встроенной RGB подсветкой Chroma по периметру.',
		features: {
			type: 'Гибридный (ткань/полимер)',
			size: 'XL (940x410x3 мм)',
			surface: 'Скоростное',
			base: 'Резиновая',
			stichedEdges: true,
			design: 'Черный, RGB подсветка',
		},
		image: '/images/razer-strider-chroma.jpg',
		inStock: true,
		discount: 0,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: true,
	},
	{
		id: 40,
		name: 'Artisan Hien Soft XL',
		category: 'Коврики',
		price: 11990,
		brand: 'Artisan',
		rating: 4.9,
		description: 'Коврик ручной работы из Японии. Знаменитая поверхность Hien обеспечивает невероятную скорость и контроль одновременно, практически не изнашивается.',
		features: {
			type: 'Гибридный',
			size: 'XL (490x420x4 мм)',
			surface: 'Скоростное с контролем',
			base: 'Натуральный каучук',
			stichedEdges: true,
			design: 'Красный',
		},
		image: '/images/artisan-hien.jpg',
		inStock: false,
		discount: 0,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 41,
		name: 'Lethal Gaming Gear Saturn Pro',
		category: 'Коврики',
		price: 8990,
		brand: 'Lethal Gaming Gear',
		rating: 4.8,
		description: 'Пористая пенопластовая основа (sponge base) для максимального комфорта и контроля. Поверхность из мягкого полиэстера для плавного скольжения.',
		features: {
			type: 'Тканевый (poron base)',
			size: 'XXL (500x500x4.5 мм)',
			surface: 'Контролируемое',
			base: 'Пористый пенопласт (Poron)',
			stichedEdges: true,
			design: 'Серый космос',
		},
		image: '/images/lgg-saturn-pro.jpg',
		inStock: true,
		discount: 5,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: true,
	},
	{
		id: 42,
		name: 'HyperX Fury S Pro',
		category: 'Коврики',
		price: 1990,
		brand: 'HyperX',
		rating: 4.6,
		description: 'Доступный и качественный тканевый коврик с простроченными краями. Отличное соотношение цены и качества.',
		features: {
			type: 'Тканевый',
			size: 'Large (450x400x4 мм)',
			surface: 'Сбалансированное',
			base: 'Резиновая',
			stichedEdges: true,
			design: 'Черный',
		},
		image: '/images/hyperx-fury-s.jpg',
		inStock: true,
		discount: 25,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},

	// ИГРОВЫЕ КОВРИКИ-ПОДСТАВКИ (Deskpad) (4 товара)
	{
		id: 43,
		name: 'Glorious Extended Gaming Mat',
		category: 'Коврики',
		price: 4490,
		brand: 'Glorious',
		rating: 4.7,
		description: 'Огромная эстетичная подставка под клавиатуру и мышь. Защищает стол и создает целостный игровой образ.',
		features: {
			type: 'Тканевый (Deskpad)',
			size: 'Extended (900x400x3 мм)',
			surface: 'Сбалансированное',
			base: 'Резиновая',
			stichedEdges: true,
			design: 'Аниме / Темная тема',
		},
		image: '/images/glorious-deskpad.jpg',
		inStock: true,
		discount: 0,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: true,
	},
	{
		id: 44,
		name: 'Razer Gigantus V2 XXL',
		category: 'Коврики',
		price: 5490,
		brand: 'Razer',
		rating: 4.5,
		description: 'Масштабная подставка с микротекстурной поверхностью, оптимизированной для точности. Легко чистится.',
		features: {
			type: 'Тканевый (Deskpad)',
			size: 'XXL (1000x500x3 мм)',
			surface: 'Контролируемое',
			base: 'Резиновая',
			stichedEdges: false,
			design: 'Черный матовый',
		},
		image: '/images/razer-gigantus-v2-xxl.jpg',
		inStock: true,
		discount: 15,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},

	// ВЕБ-КАМЕРЫ (4 товара)
	{
		id: 45,
		name: 'Logitech C922 Pro Stream',
		category: 'Веб-камеры',
		price: 7990,
		brand: 'Logitech',
		rating: 4.7,
		description: 'Популярная веб-камера для стриминга с поддержкой записи в 1080p 60fps и функцией фонового замещения (без зеленого экрана).',
		features: {
			resolution: '1080p 60fps / 720p 30fps',
			matrix: 'CMOS',
			microphone: 'Стерео',
			connection: 'USB',
			fov: '78°',
			autoFocus: true,
			hdr: false,
		},
		image: '/images/logitech-c922.jpg',
		inStock: true,
		discount: 20,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 46,
		name: 'Razer Kiyo Pro',
		category: 'Веб-камеры',
		price: 12990,
		brand: 'Razer',
		rating: 4.6,
		description: 'Веб-камера с большой светосилой (f/2.0) и HDR для отличного качества изображения даже при слабом освещении. Настраиваемое поле зрения.',
		features: {
			resolution: '1080p 60fps',
			matrix: 'Sony Starvis',
			microphone: 'Направленный',
			connection: 'USB',
			fov: '103°/90°/80°',
			autoFocus: true,
			hdr: true,
		},
		image: '/images/razer-kiyo-pro.jpg',
		inStock: true,
		discount: 0,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: true,
	},
	{
		id: 47,
		name: 'Elgato Facecam',
		category: 'Веб-камеры',
		price: 17990,
		brand: 'Elgato',
		rating: 4.8,
		description: 'Камера, созданная специально для стримеров. Несжатый видеопоток, фиксированная фокусировка, отличная светочувствительность и настройка через приложение.',
		features: {
			resolution: '1080p 60fps',
			matrix: 'Sony',
			microphone: 'Нет',
			connection: 'USB 3.0',
			fov: '82°',
			autoFocus: false,
			hdr: false,
		},
		image: '/images/elgato-facecam.jpg',
		inStock: false,
		discount: 10,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},

	// МИКРОФОНЫ (4 товара)
	{
		id: 48,
		name: 'HyperX QuadCast',
		category: 'Микрофоны',
		price: 9990,
		brand: 'HyperX',
		rating: 4.7,
		description: 'USB-конденсаторный микрофон для стримеров. Имеет встроенный антивибрационный подвес, регулятор гейна, тумблер отключения звука и 4 режима направленности.',
		features: {
			type: 'Конденсаторный (USB)',
			polarPattern: 'Стерео/Кардиоидная/Всенаправленная/Двунаправленная',
			frequency: '20Hz–20kHz',
			connection: 'USB',
			monitoring: '3.5mm jack',
			mount: 'Встроенный амортизатор',
			popFilter: 'Встроенный',
		},
		image: '/images/hyperx-quadcast.jpg',
		inStock: true,
		discount: 15,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 49,
		name: 'Razer Seiren V2 Pro',
		category: 'Микрофоны',
		price: 14990,
		brand: 'Razer',
		rating: 4.5,
		description: 'Профессиональный USB-микрофон с высококачественным преобразователем. В комплекте идет поп-фильтр и регулируемая стойка.',
		features: {
			type: 'Конденсаторный (USB)',
			polarPattern: 'Суперкардиоидная',
			frequency: '20Hz–20kHz',
			connection: 'USB-C',
			monitoring: '3.5mm jack',
			mount: 'Стойка в комплекте',
			popFilter: 'В комплекте',
		},
		image: '/images/razer-seiren-v2-pro.jpg',
		inStock: true,
		discount: 0,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: true,
	},
	{
		id: 50,
		name: 'Elgato Wave:3',
		category: 'Микрофоны',
		price: 13990,
		brand: 'Elgato',
		rating: 4.8,
		description: 'Компактный USB-микрофон с революционной функцией мониторинга Clipguard (защита от клиппинга), capacitive mute и мощным ПО Wave Link для управления аудио.',
		features: {
			type: 'Конденсаторный (USB)',
			polarPattern: 'Кардиоидная',
			frequency: '70Hz–20kHz',
			connection: 'USB-C',
			monitoring: '3.5mm jack',
			mount: 'Резьба 3/8" и 5/8"',
			popFilter: 'Опционально',
		},
		image: '/images/elgato-wave-3.jpg',
		inStock: true,
		discount: 8,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
	{
		id: 51,
		name: 'Fifine K688',
		category: 'Микрофоны',
		price: 4490,
		brand: 'Fifine',
		rating: 4.4,
		description: 'Бюджетный XLR/USB комплект для начинающих стримеров и подкастеров. Включает микрофон, подвес, поп-фильтр, кабели и стойку.',
		features: {
			type: 'Конденсаторный (XLR/USB)',
			polarPattern: 'Кардиоидная',
			frequency: '20Hz–20kHz',
			connection: 'XLR / USB (комбо)',
			monitoring: 'Нет',
			mount: 'Подвес в комплекте',
			popFilter: 'В комплекте',
		},
		image: '/images/fifine-k688.jpg',
		inStock: true,
		discount: 30,
		get finalPrice() {
			return this.price * (1 - this.discount / 100)
		},
		isNew: false,
	},
]
